### ISSUE TITLE
Default Hostgroup breaks Discovery when force_environment is set

### ISSUE THREAD

**Issue by cyberkov** [theforeman/foreman_default_hostgroup#49]
Hello!

I just discovered the following error when force_environment is set to true:
![grafik](https://user-images.githubusercontent.com/312590/134076630-41e41235-618b-4a92-8a59-f50c94693ab8.png)

```
2021-09-20T21:21:40 [W|app|23702c25] Host discovery failed, facts: {"os"=>{"release"=>{"full"=>"7.9.2009", "major"=>"7", "minor"=>"9"}, "name"=>"CentOS", "family"=>"RedHat", "architecture"=>"x86_64",. [...]
2021-09-20T21:21:40 [I|app|23702c25] Backtrace for 'Host discovery failed, facts: {"os"=>{"release"=>{"full"=>"7.9.2009", "major"=>"7", [...]  "discovery_proxy_type"=>"foreman", "_type"=>:foreman_discovery}' error (NoMethodError): undefined method `environment=' for #<Host::Discovered:0x00007f91eca8f2e8>
 23702c25 | Did you mean?  environment_id=
 23702c25 |                environment_id
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/activemodel-6.0.3.4/lib/active_model/attribute_methods.rb:432:in `method_missing'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/audited-4.9.0/lib/audited/auditor.rb:99:in `method_missing'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_default_hostgroup-6.0.0/lib/default_hostgroup_base_host_patch.rb:38:in `import_facts'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_default_hostgroup-6.0.0/lib/default_hostgroup_base_host_patch.rb:8:in `import_facts'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_discovery-16.3.4/app/services/foreman_discovery/host_fact_importer.rb:8:in `import_facts'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_discovery-16.3.4/app/models/host/discovered.rb:100:in `import_host'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_discovery-16.3.4/app/controllers/api/v2/discovered_hosts_controller.rb:110:in `block in facts'
 23702c25 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:108:in `as'
 23702c25 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:114:in `as_anonymous_admin'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_discovery-16.3.4/app/controllers/api/v2/discovered_hosts_controller.rb:109:in `facts'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/actionpack-6.0.3.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/actionpack-6.0.3.4/lib/abstract_controller/base.rb:195:in `process_action'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/actionpack-6.0.3.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
 23702c25 | /opt/theforeman/tfm/root/usr/share/gems/gems/actionpack-6.0.3.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[...]
```

I fixed this by patching the [lib/default_hostgroup_base_host_patch.rb](https://github.com/theforeman/foreman_default_hostgroup/blob/develop/lib/default_hostgroup_base_host_patch.rb#L38) with
```ruby
self.host.environment = new_hostgroup.environment if Setting[:force_host_environment] == true and facts[:_type] != :foreman_discovery
```
but I am not entirely sure if there isn't some other mechnism to ensure default_hostgroups leaves this fact import alone :-)

Best wishes
Hannes

**Comment by lzap** [comment]
Thanks, that plugin is not in wide use and it is not well tested. I am closing this issue since you opened a PR, thanks!
